#!/usr/bin/env bash

set -eux

ninja


ARR=(
    "charrdos_delaying"
    "udpsdos_injection"
    "charrdos_injection"
    "ipidaddr_delaying"
    "plankton_delaying"
    "udpsdos_insertion"
    "charrdos_insertion"
    "ipidaddr_injection"
    "plankton_injection"
    "udpsdos_padding"
    "charrdos_padding"
    "ipidaddr_insertion"
    "plankton_insertion"
    "vlc_lrscan_delaying"
    "crossfiremd_delaying"
    "ipidaddr_padding"
    "plankton_padding"
    "vlc_lrscan_injection"
    "crossfiremd_injection"
    "lrtcpdos02_delaying"
    "sality_delaying"
    "vlc_lrscan_insertion"
    "crossfiremd_insertion"
    "lrtcpdos02_injection"
    "sality_injection"
    "vlc_lrscan_padding"
    "crossfiremd_padding"
    "lrtcpdos02_insertion"
    "sality_insertion"
    "wannalocker_delaying"
    "lrtcpdos02_padding"
    "sality_padding"
    "wannalocker_injection"
    "icmpscan_delaying"
    "ntprdos_delaying"
    "sshpwdsm_delaying"
    "wannalocker_insertion"
    "icmpscan_injection"
    "ntprdos_injection"
    "sshpwdsm_injection"
    "wannalocker_padding"
    "icmpscan_insertion"
    "ntprdos_insertion"
    "sshpwdsm_insertion"
    "webshell_delaying"
    "icmpscan_padding"
    "ntprdos_padding"
    "sshpwdsm_padding"
    "webshell_injection"
    "icmpsdos_delaying"
    "oracle_delaying"
    "telnetpwdmd_delaying"
    "webshell_insertion"
    "icmpsdos_injection"
    "oracle_injection"
    "telnetpwdmd_injection"
    "webshell_padding"
    "icmpsdos_insertion"
    "oracle_insertion"
    "telnetpwdmd_insertion"
    "icmpsdos_padding"
    "oracle_padding"
    "telnetpwdmd_padding"
    "udpsdos_delaying"
)

for item in ${ARR[@]}; do
    ./HyperVision -config /home/sduu2/userspace-20T-1/yyr/HyperVision_Cpp/configuration/evasion/${item}.json > ../cache/${item}.log # &
done
